INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-01-04', 'Samya', -30, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-01-12', 'Sara', -50, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-01-21', 'Young Brother', -15, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-01-21', 'Uncle Issa', -40, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-01-22', 'Father', -55, 'Nam nulla.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-01-23', 'Father', -50, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae Duis faucibus accumsan odio.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-01-23', 'Sara', 75, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-01-30', 'Mila', 70, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-02-02', 'Young Brother', -35, 'Vivamus in felis eu sapien cursus vestibulum.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-02-03', 'Ahmad', -25, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-02-04', 'Mila', -15, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-02-12', 'Issa', 50, 'Curabitur gravida nisi at nibh.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-02-19', 'Lina', -5, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-02-26', 'Sara', 35, 'Duis consequat dui nec nisi volutpat eleifend.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-03-03', 'Sara', 5, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae Duis faucibus accumsan odio.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-03-04', 'Aunt Mina', -20, 'Integer non velit.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-03-04', 'Lina', 20, 'Integer non velit.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-03-12', 'Father', 5, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-03-15', 'Sara', 35, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-03-17', 'Job', 65, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-03-19', 'Sara', 70, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-03-23', 'Issa', -15, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-03-26', 'Mahmoud', 15, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-03-30', 'Issa', 30, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-04-03', 'Issa', -60, 'Donec semper sapien a libero.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-04-04', 'Landlord', -25, 'Nulla tellus.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-04-10', 'Young Brother', 45, 'In congue.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-04-11', 'Ahmad Gym', 25, 'Curabitur convallis.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-04-13', 'Young Brother', -45, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-04-17', 'Job', -30, 'Nulla suscipit ligula in lacus.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-04-19', 'Issa', -10, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-04-19', 'Uncle Issa', 5, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-04-20', 'Aunt Mina', -25, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-04-26', 'Sara', 80, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-05-03', 'Ahmad', 50, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-05-06', 'Mahmoud', 45, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-05-08', 'Job', -20, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-05-10', 'Uncle Issa', 80, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-05-13', 'Mahmoud', 25, 'Donec ut dolor.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-05-16', 'Abd', 75, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-05-17', 'Abd', -40, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-05-19', 'Father', -35, 'Vivamus in felis eu sapien cursus vestibulum.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-05-21', 'Mila', 65, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-05-27', 'Sara', 60, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-05-29', 'Mahmoud', 50, 'Sed vel enim sit amet nunc viverra dapibus.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-06-05', 'Uncle Issa', -10, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-06-10', 'Sara', 5, 'Praesent lectus.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-06-11', 'Ahmad', 15, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-06-14', 'Job', -45, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-06-14', 'Father', 5, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-06-19', 'Aunt Mina', -45, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-06-21', 'Aunt Mina', 30, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-06-22', 'Ahmad', -50, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-06-22', 'Uncle Issa', 10, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-06-25', 'Ahmad Gym', 55, 'Quisque porta volutpat erat.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-06-26', 'Ahmad', 65, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-06-28', 'Sara', 75, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-06-28', 'Sara', 15, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-06-28', 'Sara', 15, 'Cras non velit nec nisi vulputate nonummy.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-07-04', 'Sara', 65, 'Proin eu mi.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-07-19', 'Job', -55, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-07-21', 'Uncle Issa', 5, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-07-25', 'Aunt Mina', -15, 'Maecenas pulvinar lobortis est.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-07-26', 'Lina', -10, 'Curabitur in libero ut massa volutpat convallis.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-07-27', 'Landlord', -35, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-07-29', 'Mila', -5, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-07-31', 'Ahmad Gym', -15, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-08-04', 'Mila', -30, 'Donec quis orci eget orci vehicula condimentum.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-08-05', 'Ahmad', -30, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-08-08', 'Samya', 60, 'Maecenas pulvinar lobortis est.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-08-08', 'Mila', 55, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-08-11', 'Mila', -60, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-08-12', 'Father', 55, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-08-13', 'Sara', -45, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-08-15', 'Young Brother', -25, 'Nulla suscipit ligula in lacus.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-08-16', 'Abd', 50, 'Phasellus id sapien in sapien iaculis congue.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-08-16', 'Mahmoud', -15, 'Phasellus in felis.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-08-18', 'Abd', 20, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-08-20', 'Job', -40, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-08-20', 'Uncle Issa', -60, 'Nulla tempus.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-09-01', 'Sara', 75, 'Proin interdum mauris non ligula pellentesque ultrices.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-09-06', 'Landlord', 55, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-09-08', 'Mahmoud', -55, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-09-09', 'Father', -35, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-09-15', 'Young Brother', -40, 'Aenean auctor gravida sem.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-09-21', 'Samya', 15, 'Duis ac nibh.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-09-21', 'Ahmad Gym', 75, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-09-23', 'Uncle Issa', 25, 'Ut tellus.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-09-28', 'Father', 65, 'Phasellus sit amet erat.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-09-30', 'Uncle Issa', -20, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-10-02', 'Job', 20, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-10-04', 'Sara', -10, 'Integer tincidunt ante vel ipsum.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-10-08', 'Abd', -30, 'Etiam pretium iaculis justo.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-10-08', 'Abd', -30, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-10-09', 'Abd', -5, 'Aenean auctor gravida sem.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-10-10', 'Sara', 65, 'Sed vel enim sit amet nunc viverra dapibus.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-10-10', 'Lina', 65, 'Quisque porta volutpat erat.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-10-11', 'Ahmad Gym', -45, 'Sed ante.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-10-12', 'Young Brother', 25, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-10-12', 'Sara', 55, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-10-15', 'Abd', 25, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-10-17', 'Ahmad', 105, 'Aenean sit amet justo.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-10-17', 'Mahmoud', -10, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-10-18', 'Ahmad Gym', -10, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-10-22', 'Mila', 30, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-10-23', 'Ahmad Gym', 25, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-10-24', 'Sara', -40, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-10-25', 'Sara', -40, 'Donec semper sapien a libero.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-10-29', 'Issa', 70, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-11-07', 'Ahmad', 20, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-11-10', 'Mila', 30, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-11-19', 'Job', 5, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-11-21', 'Sara', 5, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-11-22', 'Lina', 5, 'Nullam molestie nibh in lectus.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-11-22', 'Young Brother', 125, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-11-27', 'Job', -55, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-12-08', 'Lina', 40, 'Phasellus sit amet erat.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-12-11', 'Father', -60, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-12-12', 'Job', 55, 'Nullam sit amet turpis elementum ligula vehicula consequat.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-12-21', 'Landlord', -40, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-12-24', 'Sara', -45, 'Nulla suscipit ligula in lacus.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2024-12-31', 'Young Brother', 70, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2024-12-31', 'Sara', 70, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-01-04', 'Aunt Mina', 45, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-01-06', 'Aunt Mina', -45, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-01-07', 'Samya', 20, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-01-11', 'Father', -30, 'Nulla ut erat id mauris vulputate elementum.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-01-13', 'Ahmad Gym', 5, 'Sed vel enim sit amet nunc viverra dapibus.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-01-13', 'Young Brother', -45, 'Suspendisse potenti.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-01-16', 'Issa', -40, 'Praesent lectus.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-01-18', 'Ahmad', -5, 'Vestibulum ac est lacinia nisi venenatis tristique.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-01-21', 'Young Brother', -55, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-01-23', 'Sara', 5, 'Suspendisse potenti.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-01-28', 'Sara', 15, 'Cras non velit nec nisi vulputate nonummy.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-01-30', 'Landlord', 65, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-02-01', 'Aunt Mina', -10, 'Vivamus vestibulum sagittis sapien.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-02-03', 'Mahmoud', 5, 'Donec ut mauris eget massa tempor convallis.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-02-03', 'Issa', 55, 'Praesent lectus.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-02-08', 'Job', 75, 'Nullam molestie nibh in lectus.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-02-18', 'Lina', 30, 'In congue.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-02-22', 'Samya', -45, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-03-07', 'Lina', 80, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-03-09', 'Job', 15, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-03-12', 'Lina', -10, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-03-16', 'Ahmad Gym', 10, 'Praesent lectus.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-03-16', 'Father', 40, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-03-22', 'Ahmad', -50, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-03-23', 'Young Brother', -60, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-03-23', 'Sara', -10, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-03-25', 'Abd', -25, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-03-30', 'Abd', 65, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-04-01', 'Mila', -55, 'Curabitur gravida nisi at nibh.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-04-03', 'Sara', 10, 'Integer ac leo.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-04-05', 'Lina', 20, 'Aliquam erat volutpat.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-04-09', 'Landlord', -25, 'Nulla facilisi.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-04-11', 'Samya', -20, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-04-11', 'Job', 35, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-04-14', 'Lina', -30, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-04-15', 'Sara', 10, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-04-17', 'Samya', 30, 'Duis bibendum.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-04-19', 'Uncle Issa', -10, 'Duis at velit eu est congue elementum.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-04-25', 'Issa', -10, 'Maecenas rhoncus aliquam lacus.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-04-27', 'Father', 50, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-04-29', 'Mahmoud', -45, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-05-02', 'Sara', -35, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-05-12', 'Uncle Issa', -10, 'In hac habitasse platea dictumst.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-05-15', 'Landlord', -45, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-05-17', 'Sara', 75, 'Phasellus sit amet erat.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-05-19', 'Mahmoud', 60, 'Duis mattis egestas metus.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-05-22', 'Sara', -25, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-05-24', 'Issa', 55, 'Duis bibendum.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-05-27', 'Issa', -170, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-05-30', 'Aunt Mina', -55, 'Sed accumsan felis.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-06-01', 'Ahmad Gym', -10, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-06-03', 'Mila', 30, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-06-05', 'Ahmad', -50, 'Vivamus vel nulla eget eros elementum pellentesque.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-06-10', 'Mahmoud', -55, 'Cras pellentesque volutpat dui.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-06-11', 'Mahmoud', 30, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-06-13', 'Samya', -15, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-06-15', 'Mahmoud', 50, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-06-20', 'Issa', 45, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-06-21', 'Samya', 65, 'Morbi a ipsum.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-06-21', 'Lina', -10, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-06-22', 'Ahmad Gym', -35, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-06-26', 'Young Brother', 50, 'Nullam porttitor lacus at turpis.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-07-03', 'Aunt Mina', 5, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-07-03', 'Young Brother', 5, 'Sed sagittis.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-07-04', 'Ahmad Gym', -25, NULL, 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-07-10', 'Uncle Issa', 40, 'Suspendisse potenti.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-07-22', 'Aunt Mina', 75, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-07-22', 'Ahmad Gym', -40, 'Quisque porta volutpat erat.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-07-24', 'Sara', 15, 'Aliquam sit amet diam in magna bibendum imperdiet.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-07-29', 'Aunt Mina', 65, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-07-30', 'Landlord', 50, 'Fusce posuere felis sed lacus.', 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-08-03', 'Aunt Mina', 10, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-08-14', 'Sara', 50, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-08-22', 'Ahmad Gym', 50, 'Sed ante.', 'Credited');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-08-24', 'Father', 45, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(2, '2025-08-25', 'Abd', 55, NULL, 'Received');
INSERT INTO debts_log(user_id, date, party, amount, notes, type) VALUES(1, '2025-08-25', 'Sara', 20, 'Fusce consequat.', 'Credited');
